- name: "Installing mongodb on the node"
  apt:
    name: mongodb
    state: present

- name: "Copying restart script"
  copy:
    src: ../files/restart.sh
    dest: /root/restart.sh
    owner: root
    group: root
    mode: 0755
