- name: "Copying rs initiate script"
  copy: src=../files/rs_initiate.sh dest=/tmp/rs_initiate.sh mode=0755 owner=root group=root

- name: "Initiating primary node replication"
  command: /tmp/rs_initiate.sh
