- name: "Copying rs register script"
  template:
    src: "{{rsRegisterScript}}"
    dest: /root/rs_register.sh
    owner: root
    group: root
    mode: 0755

- name: "Initiating secondary node registration"
  command: /root/rs_register.sh
